DROP SEQUENCE SCORESEQ;
DROP TABLE TB_SCORE;

CREATE SEQUENCE SCORESEQ;

--번호, 이름, 나이, 성별, 지역, 직업, 전화번호, 이메일
CREATE TABLE TB_SCORE(
	S_NAME VARCHAR2(100) NOT NULL,
	S_KOR NUMBER NOT NULL, 
	S_ENG NUMBER NOT NULL,
	S_MATH NUMBER NOT NULL,
	S_SUM NUMBER,
	S_AVG NUMBER,
	S_GRADE VARCHAR2(2) CHECK (S_GRADE IN('A','B','C','D','F'))
);


ALTER TABLE TB_MEMBER
RENAME COLUMN M_AVG TO M_AGE;

INSERT INTO TB_SCORE
VALUES('위영석',100,100,100,300,100.00,'A');

INSERT INTO TB_SCORE
VALUES('성수민',80,80,80,240,80.00,'B');

INSERT INTO TB_SCORE
VALUES('김지후',40,60,70,170,56.67,'F');

INSERT INTO TB_SCORE
VALUES('정윤식',80,70,60,210,70.00,'C');
-- MEMBERSEQ.NEXTVAL이 M_NO를 자동으로 늘어나게 해줌
-- 시퀀스는 인서트 실패해도 늘어남

SELECT  S_NAME, S_KOR, S_ENG, S_MATH, S_SUM, S_AVG,S_GRADE
FROM TB_SCORE

SELECT R, S_NAME, S_KOR, S_ENG, S_MATH, S_SUM, S_AVG,S_GRADE
FROM (SELECT ROWNUM AS R, S_NAME, S_KOR, S_ENG, S_MATH, S_SUM, S_AVG,S_GRADE
	FROM 
	(SELECT  S_NAME, S_KOR, S_ENG, S_MATH, S_SUM, S_AVG,S_GRADE
	FROM TB_SCORE
	ORDER BY S_AVG DESC) A
	) B
WHERE R=2;

